pipeline {
    agent any
    
    stages {
        stage('Criando uma pagina estatica') {
            steps {
                script {
                    // Cria um diretório para a página estática
                    sh 'mkdir -p my-static-site'
                    // Cria um arquivo HTML simples
                    writeFile file: 'my-static-site/index.html', text: '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Static Site</title>
</head>
<body>
    <h1>Hello, World!</h1>
    <p>This is a simple static page generated by Jenkins.</p>
</body>
</html>'''
                }
            }
        }
        
        stage('Iniciando um HTTP Server') {
            steps {
                script {
                    // Inicia o servidor HTTP simples do Python
                    sh 'python3 -m http.server 8080 -d my-static-site &'
                }
            }
        }
    }
    
    post {
        always {
            // Pipeline conluída
            echo 'Pipeline finished. Visit http://localhost:8080 to see the static site.'
        }
    }
}
